import TutteFormalization.Homotopy.Elementary

namespace TutteFormalization.Homotopy
variable {α : Type*} {M : Matroid α} [M.Finite]

/-- Insert a closed loop at the common vertex of two contexts. -/
def insertLoop (a b l : TuttePath M) (hab : a.terminus = b.origin)
    (hal : a.terminus = l.origin) (hl : Closed l) : TuttePath M :=
  (a.concat l hal).concat b (by simpa using hl.symm.trans (hal.symm.trans hab))

/-- One permitted contextual insertion; deletion is supplied by symmetry of the
finite generated relation below. No invalid words are ever intermediate states. -/
inductive ElementaryStep (M : Matroid α) [M.Finite] (Γ : Set (Set α)) :
    TuttePath M → TuttePath M → Prop
  | insert (a b l : TuttePath M) (hab : a.terminus = b.origin)
      (hal : a.terminus = l.origin) (hl : Elementary M Γ l)
      (ha : a.Off (cutPlus M Γ)) (hb : b.Off (cutPlus M Γ)) :
      ElementaryStep M Γ (a.concat b hab) (insertLoop a b l hab hal hl.closed)

/-- The least equivalence generated by the allowed insertions on off-cut paths.
A proof is a finite derivation. Reflexivity is restricted to the off-cut domain. -/
inductive Homotopic (M : Matroid α) [M.Finite] (Γ : Set (Set α)) :
    TuttePath M → TuttePath M → Prop
  | refl (p) (off : p.Off (cutPlus M Γ)) : Homotopic M Γ p p
  | step {p q} : ElementaryStep M Γ p q → Homotopic M Γ p q
  | symm {p q} : Homotopic M Γ p q → Homotopic M Γ q p
  | trans {p q r} : Homotopic M Γ p q → Homotopic M Γ q r → Homotopic M Γ p r

/-- Nullity is actual finite deformation to the constant at the original basepoint. -/
def NullHomotopic (M : Matroid α) [M.Finite] (Γ : Set (Set α)) (p : TuttePath M) : Prop :=
  Homotopic M Γ p (TuttePath.constant p.origin (p.isHyperplane 0))

theorem ElementaryStep.endpoints {Γ} {p q : TuttePath M} (h : ElementaryStep M Γ p q) :
    p.origin = q.origin ∧ p.terminus = q.terminus := by
  cases h
  simp [insertLoop]

theorem ElementaryStep.off {Γ} {p q : TuttePath M} (h : ElementaryStep M Γ p q) :
    p.Off (cutPlus M Γ) ∧ q.Off (cutPlus M Γ) := by
  cases h with
  | insert a b l hab hal hl ha hb =>
    exact ⟨TuttePath.concat_off ha hb hab, TuttePath.concat_off (TuttePath.concat_off ha hl.off hal) hb _⟩

theorem Homotopic.endpoints {Γ} {p q : TuttePath M} (h : Homotopic M Γ p q) :
    p.origin = q.origin ∧ p.terminus = q.terminus := by
  induction h with
  | refl => exact ⟨rfl, rfl⟩
  | step h => exact h.endpoints
  | symm h ih => exact ⟨ih.1.symm, ih.2.symm⟩
  | trans h k ih ik => exact ⟨ih.1.trans ik.1, ih.2.trans ik.2⟩

theorem Homotopic.off {Γ} {p q : TuttePath M} (h : Homotopic M Γ p q) :
    p.Off (cutPlus M Γ) ∧ q.Off (cutPlus M Γ) := by
  induction h with
  | refl p h => exact ⟨h,h⟩
  | step h => exact h.off
  | symm h ih => exact ih.symm
  | trans h k ih ik => exact ⟨ih.1, ik.2⟩

theorem null_closed {Γ} {p : TuttePath M} (h : NullHomotopic M Γ p) : Closed p :=
  h.endpoints.2.symm

theorem constant_null {Γ} (H : Set α) (hH : IsHyperplane M H) (hoff : H ∉ Γ) :
    NullHomotopic M Γ (TuttePath.constant H hH) := by
  exact Homotopic.refl _ ((off_cutPlus _).mpr (TuttePath.constant_off hH hoff))

theorem elementary_null {Γ} {p : TuttePath M} (h : Elementary M Γ p) :
    NullHomotopic M Γ p := by
  let c := TuttePath.constant p.origin (p.isHyperplane 0)
  have hc : c.Off (cutPlus M Γ) := TuttePath.constant_off _ (h.off 0)
  have he : ElementaryStep M Γ (c.concat c rfl) (insertLoop c c p rfl rfl h.closed) :=
    ElementaryStep.insert c c p rfl rfl h hc hc
  have hc1 : c.concat c rfl = c := TuttePath.constant_concat c
  have hc2 : c.concat p rfl = p := TuttePath.constant_concat p
  have hc3 : insertLoop c c p rfl rfl h.closed = p := by
    unfold insertLoop
    simp only [hc2]
    exact TuttePath.concat_constant_eq p p.origin _ h.closed.symm
  have he' : Homotopic M Γ c p := by
    simpa only [hc1, hc3] using Homotopic.step he
  exact he'.symm

/-- S8: fixed ambient matroid, every basepoint, weak corank bound. No transport
of this hypothesis to a contraction is built into its meaning. -/
def Lower (M : Matroid α) [M.Finite] (Γ : Set (Set α)) (n : ℕ) : Prop :=
  ∀ p : TuttePath M, Closed p → p.Off Γ →
    natRank M M.E - natRank M p.carrier ≤ n → NullHomotopic M Γ p
end TutteFormalization.Homotopy
