import TutteFormalization.IndecomposableComplement

namespace TutteFormalization.Homotopy
variable {α : Type*} {M : Matroid α} [M.Finite]

/-- The auxiliary generation argument in the recognition supplement: every
indecomposable interval is generated by its indecomposable covers of the bottom.
The containing flat K is arbitrary; no entire-interval model identification is claimed. -/
theorem indecomposable_subset_of_covers_subset {D S K : Set α}
    (hD : Indecomposable M D) (hS : Indecomposable M S) (hDS : D ⊆ S)
    (hK : M.IsFlat K) (hDK : D ⊆ K)
    (covers : ∀ P, Indecomposable M P → D ⊆ P → P ⊆ S →
      natRank M P = natRank M D + 1 → P ⊆ K) : S ⊆ K := by
  generalize hn : natRank M S - natRank M D = n
  induction n using Nat.strong_induction_on generalizing S with
  | h n ih =>
    have hDSr := natRank_mono (M := M) hDS
    by_cases hzero : natRank M S = natRank M D
    · have heq := flat_eq_of_subset_of_natRank_le hD.1 hS.1 hDS (by omega)
      exact heq ▸ hDK
    by_cases hone : natRank M S = natRank M D + 1
    · exact covers S hS hDS Set.Subset.rfl hone
    have hgap : natRank M D + 2 ≤ natRank M S := by omega
    obtain ⟨T,hT,hDT,hTS,hTr⟩ := exists_indecomposable_of_rank hS hD hDS
      (natRank M S - 2) (by omega) (by omega)
    obtain ⟨U,V,hU,hV,hTU,hTV,hUS,hVS,hUV,hUr,hVr⟩ :=
      exists_indecomposable_diamond hS hT hTS (by omega)
    have hUK : U ⊆ K := ih (natRank M U - natRank M D) (by omega)
      hU (hDT.trans hTU)
      (fun P hP hDP hPU hr => covers P hP hDP (hPU.trans hUS) hr) rfl
    have hVK : V ⊆ K := ih (natRank M V - natRank M D) (by omega)
      hV (hDT.trans hTV)
      (fun P hP hDP hPV hr => covers P hP hDP (hPV.trans hVS) hr) rfl
    let J := M.closure (U ∪ V)
    have hJ : M.IsFlat J := M.isFlat_closure _
    have hUJ : U ⊆ J := M.subset_closure_of_subset' Set.subset_union_left hU.1.subset_ground
    have hVJ : V ⊆ J := M.subset_closure_of_subset' Set.subset_union_right hV.1.subset_ground
    have hJS : J ⊆ S := (M.closure_mono (Set.union_subset hUS hVS)).trans_eq hS.1.closure
    have hJK : J ⊆ K := (M.closure_mono (Set.union_subset hUK hVK)).trans_eq hK.closure
    have hUne : U ≠ J := by
      intro heq
      have hVU : V ⊆ U := hVJ.trans_eq heq.symm
      exact hUV (flat_eq_of_subset_of_natRank_le hV.1 hU.1 hVU (by omega)).symm
    have hlt := natRank_lt_of_flat_ssubset hU.1 hJ
      (Set.ssubset_iff_subset_ne.mpr ⟨hUJ,hUne⟩)
    have heq := flat_eq_of_subset_of_natRank_le hJ hS.1 hJS (by omega)
    exact heq ▸ hJK
end TutteFormalization.Homotopy
